### ISSUE TITLE
APIの申請について

### ISSUE THREAD

**Issue by SHC-matsuyama** [studyplus/Studyplus-iOS-SDK-V2#20]
スタディプラス株式会社 Studyplus APIご担当者様

はじめまして、大阪のアプリ・WEB開発会社の(株)ステークホルダーコムの松山です。

現在、弊社のお取引様のご委託を受けて、iPhone／Android学習アプリの開発を進めております。本アプリについて、Studyplusアプリにて、学習記録させたいご意向をお持ちであり、アプリ開発受託者の当方より、ご照会させていただきました。
APIの登録を進めておりますが、アイコン画像を登録しないとAPI登録が完了しません。
現在開発途中段階につきアイコン画像の登録ができないのですが、API登録と発行を進める手段はございませんでしょうか？
よろしくご検討お願い申し上げます。

**Comment by SHC-matsuyama** [comment]
スタディプラス株式会社 Studyplus APIご担当者様

先般ご確認させていただいている上記のご質問について、回答のご状況はいかがでしょうか？
ご確認のほどよろしくお願いいたします。

**Comment by koji-1009** [comment]
大変申し訳ありませんが、アプリ画像は入力が必須の項目とさせていただいております。
弊社の管理上必要な項目となりますため、ご理解いただけますようお願い申し上げます。

ref [Studyplus API 申し込みについて](https://info.studyplus.co.jp/contact/studyplus-api)
