### ISSUE TITLE
StudyplusAPIのアプリからのアクセス数や頻度の制限について

### ISSUE THREAD

**Issue by SHC-matsuyama** [studyplus/Studyplus-iOS-SDK-V2#21]
Studyplus 
Github運用ご担当者様

お世話になっております。
ステークホルダーコムの松山です。

現在弊社ではStudyplusのAPIを用いて、
アプリで学習した履歴をStudyplusに蓄積する機能を制作しております。

学習した履歴をAPIにて送信するタイミングは、ユーザー任意ではなく
アプリを終了する時に自動で送信するように検討しています。
そこでご質問なのですが、

1.ユーザー操作なく、アプリが自動でAPIを利用するような機能は、御社のポリシーやルール上問題ないでしょうか？
2.自動送信の場合、アプリ利用者が増えると、情報送信の頻度や量も必ず増えていくものとなります。
　送信における頻度や量について、具体的な制限は設けられておりますでしょうか？

以上、ご確認のほどよろしくお願いいたします。

**Comment by koji-1009** [comment]
@SHC-matsuyama 
こんにちは、Studyplus API アプリSDK開発担当です。

> 1.ユーザー操作なく、アプリが自動でAPIを利用するような機能は、御社のポリシーやルール上問題ないでしょうか？

弊社からしますと、API経由で送信されたデータがユーザーによる動作かアプリによる自動送信かを判断する術はございません。
このため、こちらの問題はSDKを組み込まれるアプリとユーザー様の間で認識を合わせる問題ではないかと思われます。

> 2.自動送信の場合、アプリ利用者が増えると、情報送信の頻度や量も必ず増えていくものとなります。
　送信における頻度や量について、具体的な制限は設けられておりますでしょうか？

現時点ではAPIの利用回数制限などは明確に設けてはおりません。
しかしながら、例えばアプリの動作中に1分毎に学習記録を投稿する、などの実装をされますと、Studyplus内のユーザーのタイムラインに過剰に投稿がなされる事態となります。
このため、具体的な基準が申し上げられず申し訳ありませんが、ある章を終えたり20問の課題を終えたりなどの『学習記録』の単位として適切なタイミングで送信していただければと考えております。

以上です。よろしくお願いいたします。

**Comment by SHC-matsuyama** [comment]
Studyplus API アプリ
SDK開発担当者様

お世話になっております。
ステークホルダーコムの松山です。

ご教示のほどありがとうございました。

>1.ユーザー操作なく、アプリが自動でAPIを利用するような機能は、御社のポリシーやルール上問題ないでしょうか？

アプリとユーザーでのすり合わせということで、仕様は開発者任意に検討できる旨、承知いたしました。

>2.送信における頻度や量について、具体的な制限は設けられておりますでしょうか？

現時点で制限がない旨、仕様上ある程度まとめて制御する旨承知いたしました。

ご回答ありがとうございました。
