### ISSUE TITLE
Studyplusアプリ上で「連携を解除」したあとの制御はどのようにすればよいでしょうか

### ISSUE THREAD

**Issue by ayano-opendna** [studyplus/Studyplus-iOS-SDK-V2#22]
お世話になっております。
OpenDNA　小泉と申します。

只今機能を実装しておりまして、開発アプリとStudyplusアプリと連携でき、学習時間を投稿できるところまで確認いたしました。
Studyplusアプリのタイムラインに投稿内容が正しく反映されています。

アプリ連携のソースコードは下記のようになっております。

```
if Studyplus.shared.isConnected() {
    // 連携済みの場合、学習時間投稿画面を表示する
    // ...
} else {
    // 連携していない場合
    Studyplus.shared.login()
}

```

その後、Studyplusアプリ上で開発アプリの「連携を解除する」を実行しました。
投稿画面が表示されますが、投稿ができずにエラーが発生します。

学習時間投稿画面の投稿処理のソースコードは下記のようになっております。

```
Studyplus.shared.post(studyRecord: record, success: {
    // 投稿後の処理
    // ...
}, failure: { error in
    print("Error Code: \(error.code()), Message: \(error.message())")
})

```

printされるエラーメッセージの内容：

-- StudyplusAPIRequest Path: https://external-api.studyplus.jp/v1/study_records, Method: POST, StatusCode: 400 --
Error Code: 8000, Message: Failed to post study record. (400 bad request)

この「Error Code: 8000」を契機として、再度、Studyplus.shared.login()　を実行すればよろしいでしょうか。
ご教示のほどよろしくお願いいたします。

**Comment by koishi** [comment]
@ayano-opendna 
Studyplusの大石です。

> この「Error Code: 8000」を契機として、再度、Studyplus.shared.login()　を実行すればよろしいでしょうか。
> ご教示のほどよろしくお願いいたします。

Studyplus側から連携が解除されたケースにつきましては、
ご質問のとおりError Codeでハンドリングしていただく必要があります。

その際の挙動としましては、御社のアプリの仕様によるものと思いますが
連携が解除されている旨のエラー表示や再接続の要否の確認、必要があれば再度ログインを行っていただければと思います。

**Comment by ayano-opendna** [comment]
早速の回答ありがとうございました！
承知しました、Error Codeでハンドリングするようにいたします。
